import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const modelPath = path.join(repoRoot, "models", "orislop_ai_classifier_v1.json");
const webTarget = path.join(repoRoot, "apps", "web", "src", "lib", "aiClassifierModel.generated.ts");
const extensionTarget = path.join(repoRoot, "apps", "extension", "src", "aiClassifierModel.generated.js");
const checkOnly = process.argv.includes("--check");

const rawModel = readFileSync(modelPath, "utf8");
const parsed = JSON.parse(rawModel);
validateModel(parsed);

const artifactHash = createHash("sha256").update(rawModel).digest("hex");
const runtimeModel = {
  schemaVersion: parsed.schemaVersion,
  modelId: parsed.modelId,
  modelType: parsed.modelType,
  trainingExamples: parsed.trainingExamples,
  positiveExamples: parsed.positiveExamples,
  negativeExamples: parsed.negativeExamples,
  artifactHash,
  intercept: parsed.intercept,
  slopThreshold: parsed.slopThreshold,
  features: parsed.features.map(({ term, idf, weight }) => ({ term, idf, weight }))
};
const runtimeJson = JSON.stringify(runtimeModel, null, 2);

const webSource = `// Generated by scripts/syncAiClassifierArtifacts.mjs. Do not edit by hand.\n`
  + `export const AI_CLASSIFIER_MODEL = ${runtimeJson} as const;\n`;
const extensionSource = `// Generated by scripts/syncAiClassifierArtifacts.mjs. Do not edit by hand.\n`
  + `(() => {\n  \"use strict\";\n  globalThis.ORISLOP_AI_CLASSIFIER_V1 = Object.freeze(${runtimeJson});\n})();\n`;

syncTarget(webTarget, webSource);
syncTarget(extensionTarget, extensionSource);

console.log(`${checkOnly ? "Verified" : "Synchronized"} AI classifier runtime artifacts (${runtimeModel.features.length} features, sha256:${artifactHash.slice(0, 12)}).`);

function syncTarget(target, expected) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (current === expected) return;
  if (checkOnly) {
    throw new Error(`Generated AI classifier artifact is stale: ${path.relative(repoRoot, target)}`);
  }
  writeFileSync(target, expected);
}

function validateModel(model) {
  if (!model || typeof model !== "object") throw new Error("AI model must be an object.");
  if (typeof model.modelId !== "string" || !model.modelId) throw new Error("AI modelId is missing.");
  if (!Number.isInteger(model.trainingExamples) || model.trainingExamples < 20) throw new Error("AI training example count is invalid.");
  if (!Number.isInteger(model.positiveExamples) || !Number.isInteger(model.negativeExamples)) throw new Error("AI class counts are invalid.");
  if (model.positiveExamples + model.negativeExamples !== model.trainingExamples) throw new Error("AI class counts do not match the training total.");
  if (typeof model.intercept !== "number" || !Number.isFinite(model.intercept)) throw new Error("AI intercept is invalid.");
  if (typeof model.slopThreshold !== "number" || model.slopThreshold <= 0 || model.slopThreshold >= 1) {
    throw new Error("AI slopThreshold must be between zero and one.");
  }
  if (!Array.isArray(model.features) || model.features.length === 0) throw new Error("AI model features are missing.");
  const terms = new Set();
  for (const feature of model.features) {
    if (!feature || typeof feature.term !== "string" || !feature.term) throw new Error("AI feature term is invalid.");
    if (terms.has(feature.term)) throw new Error(`Duplicate AI feature term: ${feature.term}`);
    terms.add(feature.term);
    if (typeof feature.idf !== "number" || !Number.isFinite(feature.idf)) throw new Error(`Invalid idf for ${feature.term}`);
    if (typeof feature.weight !== "number" || !Number.isFinite(feature.weight)) throw new Error(`Invalid weight for ${feature.term}`);
  }
}
