importScripts("aiClassifierModel.generated.js");

(() => {
  "use strict";

  const WORKER_POOL_SIZE = Math.max(2, Math.min(4, globalThis.navigator?.hardwareConcurrency || 4));
  const MAX_BATCH_SIZE = 10;

  const CLICKBAIT = [
    "you won't believe",
    "you wont believe",
    "wait for it",
    "watch till the end",
    "watch until the end",
    "this changed everything",
    "nobody talks about this",
    "before they delete this",
    "do not skip",
    "shocking",
    "insane ending",
    "the truth about",
    "part 2"
  ];
  const BRAINROT = [
    "brainrot",
    "minecraft parkour",
    "subway surfers",
    "mobile game background",
    "mobile gameplay",
    "parkour gameplay",
    "minecraft gameplay",
    "reddit story",
    "reddit stories",
    "reddit thread",
    "askreddit",
    "aita",
    "story narration",
    "silent minecraft parkour",
    "cozy sleep",
    "coziest sleep",
    "text to speech",
    "tts",
    "ai voice",
    "robot voice",
    "split screen",
    "family guy clips",
    "viral clips",
    "green screen",
    "greenscreen",
    "repost",
    "not mine",
    "credit unknown",
    "source unknown"
  ];
  const SENSORY_FILLER = [
    "satisfying background",
    "satisfying video",
    "satisfying videos",
    "satisfying compilation",
    "satisfying compilations",
    "most satisfying",
    "ranking the most satisfying",
    "oddly satisfying",
    "asmr compilation",
    "asmr",
    "cozy sleep",
    "coziest sleep"
  ];
  const AI_TERMS = [
    "ai",
    "ai generated",
    "ai-generated",
    "artificial intelligence",
    "generative ai",
    "generated with ai",
    "made with ai",
    "created with ai",
    "text to speech",
    "tts",
    "synthetic voice",
    "synthetic content",
    "voice clone",
    "ai voiceover",
    "ai voice over",
    "ai cover",
    "ai song",
    "ai music",
    "deepfake",
    "sora generated",
    "ai image",
    "ai video"
  ];
  const REPOST_LOW_ORIGINALITY = [
    "compilation",
    "clips compilation",
    "viral clips",
    "best moments",
    "no commentary",
    "source unknown",
    "credit unknown",
    "not mine",
    "reupload",
    "re-upload",
    "reposted",
    "green screen",
    "greenscreen"
  ];
  const SCAM_OR_CLAIM_BAIT = [
    "banks hate",
    "guaranteed passive income",
    "guaranteed income",
    "secret trick",
    "they don't want you to know",
    "before they delete this",
    "make money fast",
    "financial freedom",
    "cure",
    "miracle cure",
    "doctors hate"
  ];
  const PLATFORM_AI_DISCLOSURES = [
    "altered or synthetic content",
    "altered or synthetic",
    "content altered or synthetic",
    "includes altered or synthetic content",
    "this content is altered or synthetic",
    "this video may contain altered or synthetic content",
    "created or altered with ai",
    "generated or altered with ai",
    "made with artificial intelligence",
    "significantly edited or digitally generated",
    "digitally generated",
    "generated by ai",
    "ai-generated",
    "synthetic content",
    "ai-generated content",
    "ai generated content"
  ];
  const ENGAGEMENT_BAIT = [
    "like and follow",
    "subscribe for more",
    "follow for more",
    "follow for part",
    "comment below",
    "tag someone",
    "share this with"
  ];

  const RULES = [
    { label: "YouTube AI/synthetic disclosure", weight: 100, test: (text) => includesAny(text, PLATFORM_AI_DISCLOSURES) },
    { label: "Stacked slop-format pattern", weight: 42, test: (text) => hasStackedSlopFormat(text) },
    { label: "Reddit/TTS background-video format", weight: 38, test: (text) => isRedditTtsBackgroundFormat(text) },
    { label: "Long low-originality compilation", weight: 30, test: (text) => isLongLowOriginalityCompilation(text) },
    { label: "AI voice or synthetic narration", weight: 32, test: (text) => isAiNarration(text) },
    { label: "Repost or low-originality compilation", weight: 28, test: (text) => includesAny(text, REPOST_LOW_ORIGINALITY) },
    { label: "Scam or high-risk claim bait", weight: 28, test: (text) => includesAny(text, SCAM_OR_CLAIM_BAIT) },
    { label: "Clickbait wording", weight: 24, test: (text) => includesAny(text, CLICKBAIT) },
    { label: "Brainrot/slop format keywords", weight: 32, test: (text) => includesAny(text, BRAINROT) },
    { label: "Satisfying/ASMR filler context", weight: 8, test: (text) => isSensoryFiller(text) },
    { label: "Ranked sensory-list format", weight: 22, test: (text) => isRankedSensoryList(text) },
    { label: "Engagement bait language", weight: 20, test: (text) => includesAny(text, ENGAGEMENT_BAIT) },
    { label: "AI-generated content terms", weight: 34, test: (text) => hasAiSignal(text) },
    { label: "Excessive emoji pattern", weight: 10, test: (text) => emojiCount(text) >= 3 },
    { label: "Spammy capitalization or punctuation", weight: 12, test: (text, input) => /[!?]{3,}/.test(text) || allCapsWordCount([input.title, input.description].filter(Boolean).join(" ")) >= 3 },
    { label: "Repetitive title/caption", weight: 14, test: (text) => !isSongOrLyricsContext(text) && hasRepetition(text) },
    { label: "Low-information title", weight: 22, test: (_text, input) => isLowInformationTitle(input.title || "") },
    { label: "Shorts format signal", weight: 6, test: (_text, input) => parseYouTubeUrl(input.url).videoKind === "short" }
  ];
  const THRESHOLDS = {
    questionable: 30,
    skip: 60
  };
  const AI_MODEL = globalThis.ORISLOP_AI_CLASSIFIER_V1;
  const AI_MODEL_AVAILABLE = Boolean(AI_MODEL && Array.isArray(AI_MODEL.features) && AI_MODEL.features.length > 0);
  const AI_MODEL_ID = AI_MODEL?.modelId || "orislop-ai-classifier-v1";
  const AI_MODEL_INTERCEPT = Number.isFinite(AI_MODEL?.intercept) ? AI_MODEL.intercept : 0;
  const AI_MODEL_THRESHOLD = Number.isFinite(AI_MODEL?.slopThreshold) ? AI_MODEL.slopThreshold : 0.58;
  const AI_FEATURE_MAP = new Map((AI_MODEL?.features || []).map(({ term, idf, weight }) => [term, { idf, weight }]));
  const AI_STOP_WORDS = new Set(["a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "how", "i", "in", "is", "it", "my", "of", "on", "or", "the", "this", "to", "with", "you", "your"]);

  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message?.type !== "orislop.scoreBatch") {
      return false;
    }

    const candidates = Array.isArray(message.candidates)
      ? message.candidates.slice(0, MAX_BATCH_SIZE)
      : [];

    scoreBatch(candidates)
      .then((results) => {
        sendResponse({
          ok: true,
          workerCount: WORKER_POOL_SIZE,
          results
        });
      })
      .catch((error) => {
        sendResponse({
          ok: false,
          workerCount: WORKER_POOL_SIZE,
          error: error instanceof Error ? error.message : String(error),
          results: candidates.map(scoreOneCandidate)
        });
      });

    return true;
  });

  async function scoreBatch(candidates) {
    const results = new Array(candidates.length);
    let nextIndex = 0;

    async function runLane() {
      while (nextIndex < candidates.length) {
        const index = nextIndex;
        nextIndex += 1;
        results[index] = scoreOneCandidate(candidates[index]);
        await Promise.resolve();
      }
    }

    const laneCount = Math.max(1, Math.min(WORKER_POOL_SIZE, candidates.length || 1));
    await Promise.all(Array.from({ length: laneCount }, runLane));
    return results;
  }

  function scoreOneCandidate(candidate) {
    return scoreStaticSlop({
      url: candidate?.url || "",
      title: candidate?.title || "",
      description: candidate?.visibleText || "",
      channelName: candidate?.channelName || "",
      durationSeconds: candidate?.durationSeconds || null,
      strictness: "balanced"
    });
  }

  function scoreStaticSlop(input) {
    const parsed = parseYouTubeUrl(input.url);
    if (!parsed.videoId) {
      return {
        score: 0,
        recommendation: "watch",
        reasons: ["Enter a valid YouTube URL to score this item"],
        signalBreakdown: [],
        confidence: "low",
        videoId: null,
        videoKind: "unknown",
        baseScore: 0,
        stackedSignalBoost: 0,
        strictnessMultiplier: 1,
        thresholds: THRESHOLDS
      };
    }

    const text = normalize([
      input.title,
      input.description,
      parsed.videoKind === "short" ? "youtube shorts" : ""
    ].filter(Boolean).join(" "));
    const reasons = [];
    const signalBreakdown = [];
    let rawScore = 0;

    for (const rule of RULES) {
      if (rule.test(text, input)) {
        rawScore += rule.weight;
        reasons.push(rule.label);
        signalBreakdown.push({
          label: rule.label,
          points: rule.weight
        });
      }
    }

    const boostableSignalCount = reasons.filter((reason) => ![
      "Shorts format signal",
      "Satisfying/ASMR filler context"
    ].includes(reason)).length;
    const stackedSignalBoost = Math.max(0, boostableSignalCount - 2) * 4;
    const hasAiDisclosure = reasons.includes("YouTube AI/synthetic disclosure");
    const score = hasAiDisclosure ? 100 : clampScore(rawScore + stackedSignalBoost);
    const recommendation = hasAiDisclosure || score >= THRESHOLDS.skip ? "skip" : score >= THRESHOLDS.questionable ? "questionable" : "watch";
    const confidence = reasons.length >= 4 ? "high" : reasons.length >= 2 ? "medium" : "low";

    const heuristicResult = {
      score,
      recommendation,
      reasons: reasons.length > 0 ? reasons : ["No strong static slop signals found"],
      signalBreakdown,
      confidence,
      videoId: parsed.videoId,
      videoKind: parsed.videoKind,
      baseScore: rawScore,
      stackedSignalBoost,
      strictnessMultiplier: 1,
      thresholds: THRESHOLDS
    };
    return combineScore(input, heuristicResult);
  }

  function combineScore(input, heuristic) {
    const ai = runAiClassifier({
      title: input.title,
      description: input.description,
      channelName: input.channelName,
      durationSeconds: input.durationSeconds,
      isShort: heuristic.videoKind === "short"
    });
    const transcriptScore = null;
    const channelRisk = scoreChannelRisk(input.channelName || "");
    const hardAiDisclosure = heuristic.reasons.includes("YouTube AI/synthetic disclosure");
    const aiSourceScore = ai.available ? ai.score : heuristic.score;
    const finalScore = hardAiDisclosure ? 100 : clampScore(
      heuristic.score * 0.35
      + aiSourceScore * 0.45
      + (transcriptScore ?? heuristic.score) * 0.15
      + channelRisk * 0.05
    );
    const recommendation = finalScore >= THRESHOLDS.skip ? "skip" : finalScore >= THRESHOLDS.questionable ? "questionable" : "watch";
    const reasons = [
      ...heuristic.reasons.filter((reason) => reason !== "No strong static slop signals found").slice(0, 3),
      ...(ai.available ? [`AI classifier: ${ai.predictedLabel} (${ai.score}/100)`] : []),
      ...ai.topFeatures.slice(0, 2).map((feature) => `AI feature: ${feature.term} ${feature.contribution >= 0 ? "+" : ""}${feature.contribution}`)
    ];
    return {
      ...heuristic,
      score: finalScore,
      recommendation,
      reasons: reasons.length > 0 ? reasons : ["No strong combined slop signals found"],
      confidence: confidenceForCombined(heuristic, ai, finalScore),
      aiClassifierUsed: ai.available,
      spatiotemporalUsed: false,
      sourceScores: {
        heuristic: heuristic.score,
        aiClassifier: ai.available ? ai.score : null,
        transcript: transcriptScore,
        channelRisk,
        spatiotemporal: null
      },
      aiClassifier: ai,
      fallbackReasons: [
        ...(!ai.available ? [ai.reason] : []),
        "Spatiotemporal detector was not run in the browser extension path."
      ]
    };
  }

  function runAiClassifier(input) {
    if (!AI_MODEL_AVAILABLE) {
      return {
        available: false,
        modelId: AI_MODEL_ID,
        slopProbability: 0,
        score: 0,
        predictedLabel: "unavailable",
        confidence: "low",
        topFeatures: [],
        reason: "The generated local AI model was not loaded."
      };
    }
    const terms = extractAiTerms(input);
    const counts = new Map();
    for (const term of terms) {
      if (AI_FEATURE_MAP.has(term)) {
        counts.set(term, (counts.get(term) || 0) + 1);
      }
    }
    if (counts.size === 0) {
      const probability = sigmoid(AI_MODEL_INTERCEPT);
      return {
        available: true,
        modelId: AI_MODEL_ID,
        slopProbability: probability,
        score: Math.round(probability * 100),
        predictedLabel: "not_slop",
        confidence: "low",
        topFeatures: []
      };
    }
    const total = Array.from(counts.values()).reduce((sum, value) => sum + value, 0);
    const weighted = [];
    for (const [term, count] of counts) {
      const feature = AI_FEATURE_MAP.get(term);
      weighted.push([term, (count / total) * feature.idf, feature.weight]);
    }
    const norm = Math.sqrt(weighted.reduce((sum, [, value]) => sum + value * value, 0)) || 1;
    const contributions = weighted.map(([term, value, weight]) => ({ term, contribution: (value * weight) / norm }));
    const topFeatures = contributions
      .map((feature) => ({ term: feature.term, contribution: Number(feature.contribution.toFixed(3)) }))
      .sort((left, right) => Math.abs(right.contribution) - Math.abs(left.contribution))
      .slice(0, 5);
    const linear = AI_MODEL_INTERCEPT + contributions.reduce((sum, feature) => sum + feature.contribution, 0);
    const probability = sigmoid(linear);
    return {
      available: true,
      modelId: AI_MODEL_ID,
      slopProbability: probability,
      score: Math.round(probability * 100),
      predictedLabel: predictAiLabel(input, topFeatures, probability),
      confidence: Math.abs(probability - AI_MODEL_THRESHOLD) > 0.22 ? "medium" : "low",
      topFeatures
    };
  }

  function extractAiTerms(input) {
    const text = [input.title, input.description, input.channelName, ...(input.matchedSignals || [])].filter(Boolean).join(" ");
    const tokens = (text.toLowerCase().match(/[a-z0-9][a-z0-9_'-]*/g) || [])
      .filter((token) => token.length > 1 && !AI_STOP_WORDS.has(token));
    const terms = [...tokens, ...tokens.slice(0, -1).map((token, index) => `${token}_${tokens[index + 1]}`)];
    terms.push(input.isShort ? "__short__" : "__watch__");
    if (input.durationSeconds >= 1800) terms.push("__duration_long__");
    else if (input.durationSeconds > 0 && input.durationSeconds <= 75) terms.push("__duration_short__");
    else if (input.durationSeconds > 0) terms.push("__duration_medium__");
    return terms;
  }

  function predictAiLabel(input, topFeatures, probability) {
    const text = [input.title, input.description, input.channelName, ...topFeatures.map((feature) => feature.term)].join(" ").toLowerCase();
    if (probability < AI_MODEL_THRESHOLD) {
      return /\b(science|explains|tutorial|history|math|educational)\b/.test(text) ? "normal_educational" : "not_slop";
    }
    if (/\b(reddit|aita|story|minecraft|parkour|tts)\b/.test(text)) return "reddit_story";
    if (/\b(ai|voice|synthetic|deepfake|generated)\b/.test(text)) return "ai_voice";
    if (/\b(guaranteed|banks|doctors|cure|miracle|secret|trick)\b/.test(text)) return "scam_bait";
    if (/\b(repost|compilation|clips|source|unknown|credit|no_commentary)\b/.test(text)) return "repost_compilation";
    if (/\b(brainrot|subway|surfers|split|screen|viral|ranking)\b/.test(text)) return "brainrot_format";
    return "slop";
  }

  function scoreTranscript(text) {
    const normalized = normalize(text || "");
    if (normalized.length < 24) return null;
    let score = 0;
    if (/\b(ai voice|text to speech|tts|robot voice|synthetic voice)\b/.test(normalized)) score += 35;
    if (/\b(reddit|aita|storytime|askreddit)\b/.test(normalized)) score += 22;
    if (/\b(guaranteed|miracle|doctors hate|banks hate|secret trick|make money fast)\b/.test(normalized)) score += 34;
    return clampScore(score);
  }

  function scoreChannelRisk(channelName) {
    const text = normalize(channelName || "");
    let score = 0;
    if (/\b(bot|repost|vault|clips|compilation|viral loop|story bot|shortcut|secret)\b/.test(text)) score += 45;
    if (/\b(lab|class|tutor|science|history|repair|kitchen|studio|notes)\b/.test(text)) score -= 24;
    return clampScore(score);
  }

  function confidenceForCombined(heuristic, ai, finalScore) {
    if (heuristic.score >= 60 && ai.score >= 60 && finalScore >= 60) return "high";
    if (heuristic.score < 30 && ai.score < 30 && finalScore < 30) return "high";
    return ai.confidence === "low" ? heuristic.confidence : "medium";
  }

  function parseYouTubeUrl(input) {
    const trimmed = String(input || "").trim();
    if (!trimmed) {
      return emptyParsedResult();
    }

    try {
      const url = new URL(trimmed.startsWith("http") ? trimmed : `https://${trimmed}`);
      const host = url.hostname.toLowerCase();
      if (!["youtube.com", "www.youtube.com", "m.youtube.com", "youtu.be"].includes(host)) {
        return emptyParsedResult();
      }

      const pathParts = url.pathname.split("/").filter(Boolean);
      const shortsId = pathParts[0] === "shorts" && pathParts[1] ? decodeURIComponent(pathParts[1]) : null;
      const watchId = url.pathname === "/watch" ? url.searchParams.get("v") : null;
      const shortLinkId = host === "youtu.be" && pathParts[0] ? decodeURIComponent(pathParts[0]) : null;
      const videoId = sanitizeVideoId(shortsId || watchId || shortLinkId);
      const videoKind = shortsId ? "short" : videoId ? "watch" : "unknown";

      return {
        videoId,
        videoKind
      };
    } catch {
      return emptyParsedResult();
    }
  }

  function sanitizeVideoId(value) {
    if (!value) {
      return null;
    }
    const clean = value.trim();
    return /^[a-zA-Z0-9_-]{3,128}$/.test(clean) ? clean : null;
  }

  function emptyParsedResult() {
    return {
      videoId: null,
      videoKind: "unknown"
    };
  }

  function includesAny(text, phrases) {
    return phrases.some((phrase) => text.includes(phrase));
  }

  function isRedditTtsBackgroundFormat(text) {
    const hasStorySource = /\b(reddit|askreddit|aita|storytime|story|stories|thread)\b/.test(text);
    const hasBackgroundVideo = /\b(minecraft|parkour|subway surfers|mobile game|gameplay|satisfying background|silent minecraft parkour)\b/.test(text);
    const hasSyntheticNarration = /\b(text to speech|tts|ai voice|robot voice|voiceover)\b/.test(text);
    return hasStorySource && (hasBackgroundVideo || hasSyntheticNarration);
  }

  function isAiNarration(text) {
    return /\b(ai voice|ai voiceover|ai voice over|text to speech|tts|robot voice|synthetic voice|voice clone)\b/.test(text);
  }

  function hasStackedSlopFormat(text) {
    const hasStory = /\b(reddit|askreddit|aita|story|stories|thread)\b/.test(text);
    const hasBackground = /\b(minecraft|parkour|subway surfers|mobile game|gameplay)\b/.test(text);
    const hasSyntheticNarration = /\b(text to speech|tts|ai voice|robot voice|voiceover|narration)\b/.test(text);
    const hasLowOriginalitySource = /\b(viral clips|clips compilation|family guy clips|repost|reuploaded|re-upload|source unknown|credit unknown|not mine|no commentary|green screen|greenscreen)\b/.test(text);
    return [hasStory, hasBackground, hasSyntheticNarration, hasLowOriginalitySource].filter(Boolean).length >= 2;
  }

  function isLongLowOriginalityCompilation(text) {
    const hasLongDuration = /\b([1-9]|1[0-2])\s*(hour|hours|hr|hrs)\b/.test(text);
    const hasLowOriginalityTopic = /\b(reddit|stories|story|minecraft|parkour|subway surfers|viral clips|clips compilation|source unknown|credit unknown|not mine|repost|reupload|text to speech|tts|ai voice|robot voice)\b/.test(text)
      || (/\b(compilation|clips)\b/.test(text) && /\b(no commentary|source unknown|credit unknown|viral|ai voice|tts|repost|reupload)\b/.test(text));
    return hasLongDuration && hasLowOriginalityTopic;
  }

  function isSensoryFiller(text) {
    return includesAny(text, SENSORY_FILLER) && !isSongOrLyricsContext(text);
  }

  function isRankedSensoryList(text) {
    return isSensoryFiller(text)
      && /\b(ranking|ranked|top\s*\d+|most satisfying|best satisfying|satisfying compilation|asmr compilation)\b/.test(text);
  }

  function hasAiSignal(text) {
    if (includesAny(text, PLATFORM_AI_DISCLOSURES)) {
      return true;
    }
    if (includesAny(text, AI_TERMS.filter((term) => term !== "ai"))) {
      return true;
    }
    return /\bai\b/.test(text)
      && /\b(voice|generated|synthetic|deepfake|clone|cover|song|music|video|image|art|made|created|altered)\b/.test(text);
  }

  function emojiCount(text) {
    return Array.from(text).filter((char) => /\p{Extended_Pictographic}/u.test(char)).length;
  }

  function allCapsWordCount(text) {
    return text.split(/\s+/).filter((word) => /^[A-Z]{4,}$/.test(word)).length;
  }

  function hasRepetition(text) {
    const words = text.match(/[a-z0-9']+/gi)?.map((word) => word.toLowerCase()) || [];
    if (words.length < 10) {
      return false;
    }

    const uniqueRatio = new Set(words).size / words.length;
    const counts = new Map();
    for (let index = 0; index < words.length - 1; index += 1) {
      const key = `${words[index]} ${words[index + 1]}`;
      counts.set(key, (counts.get(key) || 0) + 1);
    }

    return uniqueRatio < 0.45 || Array.from(counts.values()).some((count) => count >= 3);
  }

  function isSongOrLyricsContext(text) {
    return /\b(song|songs|lyrics|chorus|verse|hook|music|track|cover|remix|karaoke|performance|practice)\b/.test(text);
  }

  function isLowInformationTitle(title) {
    const trimmed = title.trim();
    if (!trimmed) {
      return false;
    }

    const tokens = trimmed.split(/\s+/).filter(Boolean);
    const hashtagTokens = tokens.filter((token) => /^#[a-zA-Z0-9_-]+$/.test(token));
    return trimmed.length < 12
      || (tokens.length >= 2 && hashtagTokens.length === tokens.length)
      || (tokens.length >= 4 && hashtagTokens.length / tokens.length >= 0.75);
  }

  function normalize(value) {
    return String(value || "").toLowerCase().replace(/\s+/g, " ").trim();
  }

  function sigmoid(value) {
    if (value >= 0) {
      const z = Math.exp(-value);
      return 1 / (1 + z);
    }
    const z = Math.exp(value);
    return z / (1 + z);
  }

  function clampScore(value) {
    return Math.max(0, Math.min(100, Math.round(value)));
  }
})();
