(() => {
  "use strict";

  const FLAGGED_KEY = "orislop.extension.flaggedLog";
  const SKIPPED_KEY = "orislop.extension.skippedLog";
  const SETTINGS_KEY = "orislop.extension.settings";
  const PROCESSED_ATTR = "data-orislop-processed";
  const SIGNATURE_ATTR = "data-orislop-signature";
  const COMMENT_PROCESSED_ATTR = "data-orislop-comment-processed";
  const COMMENT_SIGNATURE_ATTR = "data-orislop-comment-signature";
  const ORIGINAL_DISPLAY_ATTR = "data-orislop-original-display";
  const CHILD_DISPLAY_ATTR = "data-orislop-child-display";
  const TOAST_ID = "orislop-autoskip-toast";
  const CURRENT_SKIP_SHIELD_ID = "orislop-current-skip-shield";
  const MAX_SCAN_PER_PASS = 28;
  const COMMENT_SCAN_LIMIT = 10;
  const SCAN_DEBOUNCE_MS = 280;
  const AUTOSKIP_DELAY_MS = 140;
  const BACKGROUND_RETRY_MS = 5000;
  const BACKGROUND_RESPONSE_TIMEOUT_MS = 1800;
  const MAX_CONSECUTIVE_AUTOSKIPS = 3;
  const LOOKAHEAD_LIMIT = 10;
  const WORKER_POOL_SIZE = Math.max(2, Math.min(4, navigator.hardwareConcurrency || 4));

  const DEFAULT_SETTINGS = {
    autoSkip: false,
    hideFeedCards: true,
    hideBotComments: false,
    advancedDetection: false
  };

  const CLICKBAIT = [
    "you won't believe",
    "you wont believe",
    "wait for it",
    "watch till the end",
    "watch until the end",
    "this changed everything",
    "nobody talks about this",
    "before they delete this",
    "do not skip",
    "shocking",
    "insane ending",
    "the truth about",
    "part 2"
  ];
  const BRAINROT = [
    "brainrot",
    "minecraft parkour",
    "subway surfers",
    "mobile game background",
    "mobile gameplay",
    "parkour gameplay",
    "minecraft gameplay",
    "reddit story",
    "reddit stories",
    "reddit thread",
    "askreddit",
    "aita",
    "story narration",
    "silent minecraft parkour",
    "cozy sleep",
    "coziest sleep",
    "text to speech",
    "tts",
    "ai voice",
    "robot voice",
    "split screen",
    "family guy clips",
    "viral clips",
    "green screen",
    "greenscreen",
    "repost",
    "not mine",
    "credit unknown",
    "source unknown"
  ];
  const SENSORY_FILLER = [
    "satisfying background",
    "satisfying video",
    "satisfying videos",
    "satisfying compilation",
    "satisfying compilations",
    "most satisfying",
    "ranking the most satisfying",
    "oddly satisfying",
    "asmr compilation",
    "asmr",
    "cozy sleep",
    "coziest sleep"
  ];
  const AI_TERMS = [
    "ai",
    "ai generated",
    "ai-generated",
    "artificial intelligence",
    "generative ai",
    "generated with ai",
    "made with ai",
    "created with ai",
    "text to speech",
    "tts",
    "synthetic voice",
    "synthetic content",
    "voice clone",
    "ai voiceover",
    "ai voice over",
    "ai cover",
    "ai song",
    "ai music",
    "deepfake",
    "sora generated",
    "ai image",
    "ai video"
  ];
  const REPOST_LOW_ORIGINALITY = [
    "compilation",
    "clips compilation",
    "viral clips",
    "best moments",
    "no commentary",
    "source unknown",
    "credit unknown",
    "not mine",
    "reupload",
    "re-upload",
    "reposted",
    "green screen",
    "greenscreen"
  ];
  const SCAM_OR_CLAIM_BAIT = [
    "banks hate",
    "guaranteed passive income",
    "guaranteed income",
    "secret trick",
    "they don't want you to know",
    "before they delete this",
    "make money fast",
    "financial freedom",
    "cure",
    "miracle cure",
    "doctors hate"
  ];
  const PLATFORM_AI_DISCLOSURES = [
    "altered or synthetic content",
    "altered or synthetic",
    "content altered or synthetic",
    "includes altered or synthetic content",
    "this content is altered or synthetic",
    "this video may contain altered or synthetic content",
    "created or altered with ai",
    "generated or altered with ai",
    "made with artificial intelligence",
    "significantly edited or digitally generated",
    "digitally generated",
    "generated by ai",
    "ai-generated",
    "synthetic content",
    "ai-generated content",
    "ai generated content"
  ];
  const ENGAGEMENT_BAIT = [
    "like and follow",
    "subscribe for more",
    "follow for more",
    "follow for part",
    "comment below",
    "tag someone",
    "share this with"
  ];
  const BOT_COMMENT_RULES = [
    { label: "External contact bait", weight: 35, test: (text) => /\b(telegram|whatsapp|signal|dm me|message me|text me|contact me|contact him|contact her|inbox me|reach out)\b/.test(text) },
    { label: "Suspicious external link", weight: 35, test: (text) => /(https?:\/\/|www\.|\bt\.me\b|\bwa\.me\b|\.com\b|\.net\b|\.org\b|\.xyz\b)/.test(text) },
    { label: "Finance or crypto spam", weight: 30, test: (text) => /\b(crypto|bitcoin|forex|binary option|investment|investing|trading|wallet|recovery|profit|usdt|ethereum|pump|airdrop)\b/.test(text) },
    { label: "Scam testimonial wording", weight: 25, test: (text) => /\b(i made|i earned|i recovered|thanks to|legit trader|guaranteed profit|changed my life|financial freedom)\b/.test(text) },
    { label: "Impersonation or giveaway bait", weight: 26, test: (text) => /\b(giveaway|winner|prize|claim your|selected|official support|customer care|verified agent)\b/.test(text) },
    { label: "Repeated bot wording", weight: 18, test: (text) => hasRepetition(text) },
    { label: "Excessive emoji/comment spam", weight: 12, test: (text) => emojiCount(text) >= 5 || /[!?]{4,}/.test(text) }
  ];

  const RULES = [
    { label: "YouTube AI/synthetic disclosure", weight: 100, test: (text) => includesAny(text, PLATFORM_AI_DISCLOSURES) },
    { label: "Stacked slop-format pattern", weight: 42, test: (text) => hasStackedSlopFormat(text) },
    { label: "Reddit/TTS background-video format", weight: 38, test: (text) => isRedditTtsBackgroundFormat(text) },
    { label: "Long low-originality compilation", weight: 30, test: (text) => isLongLowOriginalityCompilation(text) },
    { label: "AI voice or synthetic narration", weight: 32, test: (text) => isAiNarration(text) },
    { label: "Repost or low-originality compilation", weight: 28, test: (text) => includesAny(text, REPOST_LOW_ORIGINALITY) },
    { label: "Scam or high-risk claim bait", weight: 28, test: (text) => includesAny(text, SCAM_OR_CLAIM_BAIT) },
    { label: "Clickbait wording", weight: 24, test: (text) => includesAny(text, CLICKBAIT) },
    { label: "Brainrot/slop format keywords", weight: 32, test: (text) => includesAny(text, BRAINROT) },
    { label: "Satisfying/ASMR filler context", weight: 8, test: (text) => isSensoryFiller(text) },
    { label: "Ranked sensory-list format", weight: 22, test: (text) => isRankedSensoryList(text) },
    { label: "Engagement bait language", weight: 20, test: (text) => includesAny(text, ENGAGEMENT_BAIT) },
    { label: "AI-generated content terms", weight: 34, test: (text) => hasAiSignal(text) },
    { label: "Excessive emoji pattern", weight: 10, test: (text) => emojiCount(text) >= 3 },
    { label: "Spammy capitalization or punctuation", weight: 12, test: (text, input) => /[!?]{3,}/.test(text) || allCapsWordCount([input.title, input.description].filter(Boolean).join(" ")) >= 3 },
    { label: "Repetitive title/caption", weight: 14, test: (text) => !isSongOrLyricsContext(text) && hasRepetition(text) },
    { label: "Low-information title", weight: 22, test: (_text, input) => isLowInformationTitle(input.title || "") },
    { label: "Shorts format signal", weight: 6, test: (_text, input) => parseYouTubeUrl(input.url).videoKind === "short" }
  ];
  const THRESHOLDS = {
    questionable: 30,
    skip: 60
  };
  const AI_MODEL = globalThis.ORISLOP_AI_CLASSIFIER_V1;
  const AI_MODEL_AVAILABLE = Boolean(AI_MODEL && Array.isArray(AI_MODEL.features) && AI_MODEL.features.length > 0);
  const AI_MODEL_ID = AI_MODEL?.modelId || "orislop-ai-classifier-v1";
  const AI_MODEL_INTERCEPT = Number.isFinite(AI_MODEL?.intercept) ? AI_MODEL.intercept : 0;
  const AI_MODEL_THRESHOLD = Number.isFinite(AI_MODEL?.slopThreshold) ? AI_MODEL.slopThreshold : 0.58;
  const AI_FEATURE_MAP = new Map((AI_MODEL?.features || []).map(({ term, idf, weight }) => [term, { idf, weight }]));
  const AI_STOP_WORDS = new Set(["a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "how", "i", "in", "is", "it", "my", "of", "on", "or", "the", "this", "to", "with", "you", "your"]);

  let scanTimer = 0;
  let observeTimer = 0;
  let scanInFlight = false;
  let scanQueued = false;
  let backgroundScoringState = "unknown";
  let backgroundRetryAfter = 0;
  let candidateObserver = null;
  const observedCandidateElements = new WeakSet();
  const visibleCandidateElements = new Set();
  const preSkipScores = new Map();
  let skippedThisSession = 0;
  let settingsCache = { ...DEFAULT_SETTINGS };
  let skipController = null;
  let historyWriter = null;
  let observedVideoId = null;
  let focusBeforeSkipShield = null;
  let pageAiDisclosureCache = {
    href: "",
    at: 0,
    text: ""
  };

  if (globalThis.__ORISLOP_TEST__ === true) {
    globalThis.__ORISLOP_EXTENSION_TEST_API__ = Object.freeze({
      normalizeSettings,
      runAiClassifier,
      scoreOneCandidate
    });
  } else {
    boot();
  }

  function boot() {
    if (!globalThis.OrislopExtensionCore) {
      return;
    }
    observedVideoId = currentVideoId();
    skipController = globalThis.OrislopExtensionCore.createSkipController({
      getCurrentVideoId: currentVideoId,
      retryDelays: [AUTOSKIP_DELAY_MS, 560, 840, 1100],
      maxConsecutiveSkips: MAX_CONSECUTIVE_AUTOSKIPS,
      onStateChange: handleSkipControllerState
    });
    historyWriter = globalThis.OrislopExtensionCore.createHistoryWriter({
      readList,
      writeList: (key, records) => chrome.storage.local.set({ [key]: records })
    });
    setupCandidateObserver();
    void loadSettings().then((settings) => {
      settingsCache = settings;
      scheduleCandidateObservation();
      scheduleScan();
    });
    const observer = new MutationObserver(handlePageMutation);
    observer.observe(document.documentElement, {
      childList: true,
      subtree: true
    });
    window.addEventListener("yt-navigate-finish", handleYouTubeNavigation, { passive: true });
    window.addEventListener("yt-page-data-updated", handleYouTubeNavigation, { passive: true });
    window.addEventListener("scroll", scheduleScan, { passive: true });
    document.addEventListener("keydown", handleEscapeKey, true);
    chrome.storage.onChanged.addListener((changes, areaName) => {
      if (areaName === "local" && changes[SETTINGS_KEY]) {
        const previous = settingsCache;
        settingsCache = normalizeSettings(changes[SETTINGS_KEY].newValue);
        applySettingsChange(previous, settingsCache);
        scheduleScan();
      }
    });
  }

  function handleYouTubeNavigation() {
    syncCurrentVideoState();
    resetCandidateScanState();
    scheduleCandidateObservation();
    scheduleScan();
  }

  function handlePageMutation() {
    scheduleCandidateObservation();
    scheduleScan();
  }

  function applySettingsChange(previous, next) {
    if (previous.autoSkip && !next.autoSkip) {
      skipController?.clearPending("setting_disabled");
      preSkipScores.clear();
      removeCurrentSkipShield();
      showAutoSkipToast(
        { title: "Auto-skip disabled" },
        { score: 0 },
        "Auto-skip is off. Any pending move was cancelled."
      );
    }
    if (previous.hideFeedCards && !next.hideFeedCards) {
      restoreHiddenCards();
    }
    if (previous.hideBotComments && !next.hideBotComments) {
      restoreHiddenComments();
    }
    resetCandidateScanState();
  }

  function resetCandidateScanState() {
    for (const element of document.querySelectorAll(`[${PROCESSED_ATTR}], [${SIGNATURE_ATTR}]`)) {
      if (!(element instanceof HTMLElement) || element.getAttribute(PROCESSED_ATTR) === "revealed") {
        continue;
      }
      element.removeAttribute(PROCESSED_ATTR);
      element.removeAttribute(SIGNATURE_ATTR);
    }
    for (const element of document.querySelectorAll(`[${COMMENT_PROCESSED_ATTR}], [${COMMENT_SIGNATURE_ATTR}]`)) {
      if (!(element instanceof HTMLElement) || element.getAttribute(COMMENT_PROCESSED_ATTR) === "revealed") {
        continue;
      }
      element.removeAttribute(COMMENT_PROCESSED_ATTR);
      element.removeAttribute(COMMENT_SIGNATURE_ATTR);
    }
  }

  function syncCurrentVideoState() {
    const nextVideoId = currentVideoId();
    if (nextVideoId === observedVideoId) {
      return;
    }
    skipController?.notifyVideoChange(nextVideoId);
    observedVideoId = nextVideoId;
    removeCurrentSkipShield();
  }

  function currentVideoId() {
    return parseYouTubeUrl(window.location.href).videoId;
  }

  function handleEscapeKey(event) {
    if (event.key !== "Escape") {
      return;
    }
    const shield = document.getElementById(CURRENT_SKIP_SHIELD_ID);
    if (!shield || typeof shield._orislopWatchAnyway !== "function") {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    shield._orislopWatchAnyway("Escape pressed. Auto-skip cancelled for this video.");
  }

  function setupCandidateObserver() {
    if (!("IntersectionObserver" in window)) {
      return;
    }

    candidateObserver = new IntersectionObserver((entries) => {
      for (const entry of entries) {
        if (!(entry.target instanceof HTMLElement)) {
          continue;
        }
        if (entry.isIntersecting) {
          visibleCandidateElements.add(entry.target);
        } else {
          visibleCandidateElements.delete(entry.target);
        }
      }
      if (entries.some((entry) => entry.isIntersecting)) {
        scheduleScan();
      }
    }, {
      root: null,
      rootMargin: "900px 0px 1800px 0px",
      threshold: 0.01
    });
  }

  function scheduleCandidateObservation() {
    if (!candidateObserver) {
      return;
    }
    window.clearTimeout(observeTimer);
    observeTimer = window.setTimeout(observeCandidateElements, Math.max(SCAN_DEBOUNCE_MS, 500));
  }

  function observeCandidateElements() {
    if (!candidateObserver) {
      return;
    }

    for (const element of findCandidateElements().slice(0, MAX_SCAN_PER_PASS * 2)) {
      if (observedCandidateElements.has(element)) {
        continue;
      }
      observedCandidateElements.add(element);
      candidateObserver.observe(element);
    }
  }

  function scheduleScan() {
    window.clearTimeout(scanTimer);
    scanTimer = window.setTimeout(scanVisibleYouTubeItems, SCAN_DEBOUNCE_MS);
  }

  async function scanVisibleYouTubeItems() {
    if (scanInFlight) {
      scanQueued = true;
      return;
    }

    scanInFlight = true;
    syncCurrentVideoState();
    const candidates = findLookaheadCandidateElements();

    const jobs = [];

    try {
      for (const element of candidates) {
        if (element.getAttribute(PROCESSED_ATTR) === "revealed") {
          continue;
        }

        const extracted = extractCandidate(element);
        if (!extracted.videoId && !extracted.title && extracted.visibleText.length < 12) {
          continue;
        }

        const pendingPreSkip = getCurrentPreSkipScore(element, extracted);
        if (pendingPreSkip) {
          preSkipScores.delete(extracted.videoId);
          element.setAttribute(PROCESSED_ATTR, "true");
          void saveFlaggedRecord(extracted, pendingPreSkip);
          void attemptAutoSkip(extracted, pendingPreSkip);
          continue;
        }

        const signature = createSignature(extracted);
        if (element.getAttribute(SIGNATURE_ATTR) === signature) {
          continue;
        }

        element.setAttribute(SIGNATURE_ATTR, signature);
        element.setAttribute(PROCESSED_ATTR, "true");
        jobs.push({ element, extracted });
      }

      const scores = await scoreWithWorkers(jobs.map((job) => job.extracted));

      for (let index = 0; index < jobs.length; index += 1) {
        const { element, extracted } = jobs[index];
        if (!element.isConnected || element.getAttribute(PROCESSED_ATTR) === "revealed") {
          continue;
        }
        const score = scores[index] || scoreOneCandidate(extracted);

        if (score.recommendation === "skip") {
          const isCurrentVideo = isCurrentVideoCandidate(element, extracted);
          if (isCurrentVideo && settingsCache.autoSkip) {
            void saveFlaggedRecord(extracted, score);
            void attemptAutoSkip(extracted, score);
          } else if (isCurrentVideo) {
            markQuestionable(element, extracted, score);
            void saveFlaggedRecord(extracted, score);
          } else if (settingsCache.autoSkip && isActiveShortsScrollerCandidate(element, extracted)) {
            rememberPreSkip(extracted, score);
            void saveFlaggedRecord(extracted, score);
          } else if (settingsCache.hideFeedCards) {
            hideWithShield(element, extracted, score);
            void saveSkippedRecord(extracted, score, "hidden_card");
          } else {
            markQuestionable(element, extracted, score);
            void saveFlaggedRecord(extracted, score);
          }
        } else if (score.recommendation === "questionable") {
          if (isCurrentVideoCandidate(element, extracted)) {
            skipController?.noteNonSkipVerdict(extracted.videoId);
          }
          markQuestionable(element, extracted, score);
          void saveFlaggedRecord(extracted, score);
        } else {
          if (isCurrentVideoCandidate(element, extracted)) {
            skipController?.noteNonSkipVerdict(extracted.videoId);
          }
          clearOrislopCallout(element);
        }
      }

      scanLikelyBotComments();
    } finally {
      const shouldRescan = scanQueued;
      scanQueued = false;
      scanInFlight = false;
      if (shouldRescan) {
        scheduleScan();
      }
    }
  }

  function scanLikelyBotComments() {
    if (!settingsCache.hideBotComments) {
      return;
    }

    const comments = findVisibleCommentElements().slice(0, COMMENT_SCAN_LIMIT);
    for (const element of comments) {
      if (element.getAttribute(COMMENT_PROCESSED_ATTR) === "revealed") {
        continue;
      }

      const comment = extractComment(element);
      if (comment.text.length < 8) {
        continue;
      }

      const signature = `${comment.author}|${comment.text.slice(0, 280)}`;
      if (element.getAttribute(COMMENT_SIGNATURE_ATTR) === signature) {
        continue;
      }

      element.setAttribute(COMMENT_SIGNATURE_ATTR, signature);
      const score = scoreBotComment(comment);
      if (score.recommendation !== "bot") {
        continue;
      }

      element.setAttribute(COMMENT_PROCESSED_ATTR, "true");
      hideBotComment(element, comment, score);
      void saveSkippedRecord({
        videoId: parseYouTubeUrl(window.location.href).videoId,
        url: window.location.href,
        title: `Likely bot comment${comment.author ? ` by ${comment.author}` : ""}`,
        visibleText: comment.text
      }, {
        recommendation: "skip",
        score: score.score,
        reasons: score.reasons
      }, "hidden_bot_comment");
    }
  }

  function findVisibleCommentElements() {
    const selectors = [
      "ytd-comment-thread-renderer",
      "ytd-comment-view-model",
      "ytd-comment-renderer",
      "ytm-comment-thread-renderer",
      "ytm-comment-renderer"
    ];
    return Array.from(document.querySelectorAll(selectors.join(",")))
      .filter((element) => element instanceof HTMLElement && isCommentVisible(element));
  }

  function isCommentVisible(element) {
    const rect = element.getBoundingClientRect();
    return rect.width > 80
      && rect.height > 24
      && rect.bottom >= -250
      && rect.top <= window.innerHeight + 1100;
  }

  function extractComment(element) {
    const textNode = element.querySelector("#content-text, #content, yt-attributed-string, .yt-core-attributed-string");
    const authorNode = element.querySelector("#author-text, #author-text span, a[href^='/@'], a[href*='youtube.com/@']");
    const text = normalizeWhitespace((textNode || element).textContent || "");
    const author = normalizeWhitespace(authorNode?.textContent || "");
    return {
      author,
      text
    };
  }

  function scoreBotComment(comment) {
    const text = normalize(comment.text);
    const reasons = [];
    let score = 0;

    for (const rule of BOT_COMMENT_RULES) {
      if (rule.test(text)) {
        score += rule.weight;
        reasons.push(rule.label);
      }
    }

    const clamped = clampScore(score);
    return {
      recommendation: clamped >= 55 ? "bot" : "human_or_unclear",
      score: clamped,
      reasons: reasons.length > 0 ? reasons : ["No strong bot-comment signals found"]
    };
  }

  function hideBotComment(element, comment, score) {
    if (!element.hasAttribute(ORIGINAL_DISPLAY_ATTR)) {
      element.setAttribute(ORIGINAL_DISPLAY_ATTR, element.style.display || "");
    }

    const existing = element.querySelector(":scope > .orislop-hidden-comment");
    if (existing) {
      existing.style.display = "";
      return;
    }

    Array.from(element.children).forEach((child) => {
      if (child instanceof HTMLElement) {
        rememberChildDisplay(child);
        child.style.display = "none";
      }
    });

    const shield = document.createElement("section");
    shield.className = "orislop-hidden-comment";
    shield.setAttribute("role", "region");
    shield.setAttribute("aria-label", "Likely bot comment hidden by Orislop");

    const label = document.createElement("strong");
    label.textContent = "Likely bot comment hidden";

    const detail = document.createElement("span");
    detail.textContent = `${score.score}/100 - ${score.reasons.slice(0, 2).join(", ")}`;

    const preview = document.createElement("p");
    preview.textContent = comment.text.slice(0, 160);

    const reveal = document.createElement("button");
    reveal.type = "button";
    reveal.textContent = "Show comment";
    reveal.addEventListener("click", () => revealComment(element, shield));

    shield.append(label, detail, preview, reveal);
    element.prepend(shield);
  }

  function revealComment(element, shield) {
    shield.remove();
    restoreElementChildren(element);
    element.setAttribute(COMMENT_PROCESSED_ATTR, "revealed");
  }

  function restoreHiddenComments() {
    for (const shield of document.querySelectorAll(".orislop-hidden-comment")) {
      const element = shield.parentElement;
      if (!(element instanceof HTMLElement)) {
        continue;
      }
      shield.remove();
      restoreElementChildren(element);
      element.removeAttribute(COMMENT_PROCESSED_ATTR);
      element.removeAttribute(COMMENT_SIGNATURE_ATTR);
    }
  }

  function findCandidateElements() {
    const selectors = [
      "ytd-rich-item-renderer",
      "ytd-rich-grid-media",
      "ytd-video-renderer",
      "ytd-grid-video-renderer",
      "ytd-compact-video-renderer",
      "ytd-playlist-panel-video-renderer",
      "ytd-reel-item-renderer",
      "ytd-reel-video-renderer",
      "yt-lockup-view-model",
      "yt-lockup-metadata-view-model",
      "ytm-rich-item-renderer",
      "ytm-video-with-context-renderer",
      "ytm-compact-video-renderer",
      "ytm-shorts-lockup-view-model",
      "ytd-watch-metadata",
      "ytd-shorts"
    ];
    const elements = Array.from(document.querySelectorAll(selectors.join(",")))
      .filter((element) => element instanceof HTMLElement);
    return elements.filter((element) => !elements.some((other) => other !== element && other.contains(element)));
  }

  function findLookaheadCandidateElements() {
    const sourceElements = candidateObserver && visibleCandidateElements.size > 0
      ? Array.from(visibleCandidateElements).filter((element) => element instanceof HTMLElement && element.isConnected)
      : findCandidateElements();
    const elements = sourceElements
      .filter(isLookaheadCandidate)
      .sort((left, right) => left.getBoundingClientRect().top - right.getBoundingClientRect().top)
      .slice(0, MAX_SCAN_PER_PASS);

    const current = parseYouTubeUrl(window.location.href);
    const currentElement = current.videoId
      ? elements.find((element) => extractCandidate(element).videoId === current.videoId)
      : null;
    const ordered = currentElement
      ? [currentElement, ...elements.filter((element) => element !== currentElement)]
      : elements;

    return ordered.slice(0, LOOKAHEAD_LIMIT);
  }

  function isLookaheadCandidate(element) {
    const rect = element.getBoundingClientRect();
    return rect.width > 40
      && rect.height > 30
      && rect.bottom >= -500
      && rect.top <= window.innerHeight + 4200;
  }

  async function scoreWithWorkers(candidates) {
    if (candidates.length === 0) {
      return [];
    }

    if (backgroundScoringState === "unavailable" && Date.now() < backgroundRetryAfter) {
      return candidates.map(scoreOneCandidate);
    }

    try {
      const response = await sendScoreBatchToBackground(candidates);
      if (!response?.ok || !Array.isArray(response.results)) {
        throw new Error(response?.error || "background scoring unavailable");
      }
      backgroundScoringState = "available";
      backgroundRetryAfter = 0;
      return candidates.map((candidate, index) => response.results[index] || scoreOneCandidate(candidate));
    } catch {
      backgroundScoringState = "unavailable";
      backgroundRetryAfter = Date.now() + BACKGROUND_RETRY_MS;
      return candidates.map(scoreOneCandidate);
    }
  }

  function sendScoreBatchToBackground(candidates) {
    return new Promise((resolve, reject) => {
      let settled = false;
      const timeoutId = window.setTimeout(() => {
        if (settled) {
          return;
        }
        settled = true;
        reject(new Error("background scoring timed out"));
      }, BACKGROUND_RESPONSE_TIMEOUT_MS);
      chrome.runtime.sendMessage({
        type: "orislop.scoreBatch",
        workerCount: WORKER_POOL_SIZE,
        candidates: candidates.slice(0, LOOKAHEAD_LIMIT)
      }, (response) => {
        if (settled) {
          return;
        }
        settled = true;
        window.clearTimeout(timeoutId);
        const error = chrome.runtime.lastError;
        if (error) {
          reject(new Error(error.message));
          return;
        }
        resolve(response);
      });
    });
  }

  function scoreOneCandidate(candidate) {
    return scoreStaticSlop({
      url: candidate.url,
      title: candidate.title,
      description: candidate.visibleText,
      channelName: candidate.channelName,
      durationSeconds: candidate.durationSeconds,
      strictness: "balanced"
    });
  }

  function extractCandidate(element) {
    const link = findBestVideoLink(element);
    const title = findTitle(element, link);
    const channelName = findChannelName(element);
    const durationSeconds = findDurationSeconds(element);
    const visibleText = normalizeWhitespace(element.textContent || "");
    const aiDisclosureText = findVisibleAiDisclosureText(element);
    const parsed = parseYouTubeUrl(link || window.location.href);

    return {
      videoId: parsed.videoId,
      url: parsed.normalizedUrl || link || window.location.href,
      title,
      channelName,
      durationSeconds,
      visibleText: normalizeWhitespace([visibleText, aiDisclosureText].filter(Boolean).join(" ")),
      aiDisclosureText
    };
  }

  function findVisibleAiDisclosureText(element) {
    const candidates = [];
    const localText = normalizeWhitespace(element.textContent || "");
    if (hasPlatformAiDisclosure(localText)) {
      candidates.push(localText);
    }

    const disclosureSelectors = [
      "yt-formatted-string",
      "ytd-badge-supported-renderer",
      "ytd-metadata-row-renderer",
      "ytd-video-attribute-view-model",
      "tp-yt-paper-tooltip",
      "[aria-label]",
      "[title]"
    ];
    for (const node of element.querySelectorAll(disclosureSelectors.join(","))) {
      if (!(node instanceof HTMLElement) || !isProbablyVisible(node)) {
        continue;
      }
      const text = normalizeWhitespace([
        node.textContent || "",
        node.getAttribute("aria-label") || "",
        node.getAttribute("title") || ""
      ].join(" "));
      if (hasPlatformAiDisclosure(text)) {
        candidates.push(text);
      }
    }

    if (isCurrentVideoCandidate(element, { videoId: parseYouTubeUrl(window.location.href).videoId })) {
      const pageText = getCurrentPageAiDisclosureText();
      if (hasPlatformAiDisclosure(pageText)) {
        candidates.push(pageText);
      }
    }

    return candidates.length > 0 ? candidates[0].slice(0, 1000) : "";
  }

  function getCurrentPageAiDisclosureText() {
    const now = Date.now();
    if (pageAiDisclosureCache.href === window.location.href && now - pageAiDisclosureCache.at < 1200) {
      return pageAiDisclosureCache.text;
    }

    const selectors = [
      "ytd-watch-metadata",
      "ytd-metadata-row-container-renderer",
      "ytd-video-attribute-view-model",
      "ytd-badge-supported-renderer",
      "ytd-engagement-panel-section-list-renderer",
      "ytd-shorts [aria-label]",
      "ytd-shorts yt-formatted-string",
      "ytm-watch",
      "ytm-badge"
    ];
    const text = normalizeWhitespace(Array.from(document.querySelectorAll(selectors.join(",")))
      .slice(0, 80)
      .map((node) => node.textContent || node.getAttribute?.("aria-label") || "")
      .join(" "));
    pageAiDisclosureCache = {
      href: window.location.href,
      at: now,
      text
    };
    return text;
  }

  function findBestVideoLink(element) {
    const anchors = Array.from(element.querySelectorAll("a[href]"));
    const link = anchors.find((anchor) => {
      const href = anchor.getAttribute("href") || "";
      return href.includes("/watch?v=") || href.includes("/shorts/");
    });
    if (!link) {
      return null;
    }

    const href = link.getAttribute("href") || "";
    try {
      return new URL(href, window.location.origin).href;
    } catch {
      return null;
    }
  }

  function findTitle(element, link) {
    const titleElement = element.querySelector([
      "#video-title",
      "yt-formatted-string#video-title",
      "h3",
      "a[title]",
      "[aria-label][role='link']",
      "yt-lockup-metadata-view-model a"
    ].join(","));
    const title = titleElement?.getAttribute("title") || titleElement?.textContent || "";
    if (title.trim()) {
      return normalizeWhitespace(title);
    }

    const linkedAnchor = link
      ? Array.from(element.querySelectorAll("a[href]")).find((anchor) => {
        try {
          return new URL(anchor.getAttribute("href") || "", window.location.origin).href === link;
        } catch {
          return false;
        }
      })
      : null;
    return normalizeWhitespace(linkedAnchor?.textContent || element.getAttribute("aria-label") || "");
  }

  function findChannelName(element) {
    const channelElement = element.querySelector([
      "#channel-name",
      "ytd-channel-name",
      "yt-formatted-string.ytd-channel-name",
      "a[href^='/@']",
      "a[href*='youtube.com/@']",
      ".ytd-channel-name"
    ].join(","));
    return normalizeWhitespace(channelElement?.textContent || channelElement?.getAttribute?.("aria-label") || "");
  }

  function findDurationSeconds(element) {
    const durationElement = element.querySelector([
      "ytd-thumbnail-overlay-time-status-renderer",
      "span.ytd-thumbnail-overlay-time-status-renderer",
      ".ytd-thumbnail-overlay-time-status-renderer",
      ".badge-shape-wiz__text",
      "[aria-label*='minute']",
      "[aria-label*='second']"
    ].join(","));
    const raw = normalizeWhitespace(durationElement?.textContent || durationElement?.getAttribute?.("aria-label") || "");
    return parseDurationSeconds(raw);
  }

  function parseDurationSeconds(value) {
    const match = String(value || "").match(/\b(?:(\d{1,2}):)?(\d{1,2}):(\d{2})\b/);
    if (match) {
      const hours = Number(match[1] || 0);
      const minutes = Number(match[2] || 0);
      const seconds = Number(match[3] || 0);
      return hours * 3600 + minutes * 60 + seconds;
    }
    const minuteMatch = String(value || "").match(/\b(\d+)\s*minute/i);
    const secondMatch = String(value || "").match(/\b(\d+)\s*second/i);
    if (minuteMatch || secondMatch) {
      return Number(minuteMatch?.[1] || 0) * 60 + Number(secondMatch?.[1] || 0);
    }
    return null;
  }

  function createSignature(extracted) {
    return [
      extracted.videoId || "",
      extracted.title || "",
      extracted.channelName || "",
      extracted.durationSeconds || "",
      extracted.visibleText.slice(0, 500)
    ].join("|");
  }

  function hideWithShield(element, extracted, score) {
    if (!element.hasAttribute(ORIGINAL_DISPLAY_ATTR)) {
      element.setAttribute(ORIGINAL_DISPLAY_ATTR, element.style.display || "");
    }

    const existingShield = element.querySelector(":scope > .orislop-hidden-card");
    if (existingShield) {
      existingShield.style.display = "";
      return;
    }

    clearOrislopCallout(element);
    Array.from(element.children).forEach((child) => {
      if (child instanceof HTMLElement) {
        rememberChildDisplay(child);
        child.style.display = "none";
      }
    });

    const shield = document.createElement("section");
    shield.className = "orislop-hidden-card";
    shield.setAttribute("role", "region");
    shield.setAttribute("aria-label", "Skip-rated video hidden by Orislop");
    shield.innerHTML = "";

    const top = document.createElement("div");
    top.className = "orislop-hidden-card__top";
    const badge = document.createElement("span");
    badge.className = "orislop-hidden-card__badge";
    badge.textContent = "Hidden by Orislop";
    const scoreLabel = document.createElement("span");
    scoreLabel.className = "orislop-hidden-card__score";
    scoreLabel.textContent = `${score.score}/100`;
    top.append(badge, scoreLabel);

    const title = document.createElement("p");
    title.className = "orislop-hidden-card__title";
    title.textContent = extracted.title || "YouTube video";

    const reason = document.createElement("p");
    reason.className = "orislop-hidden-card__reason";
    reason.textContent = score.reasons.slice(0, 3).join(", ");

    const actions = document.createElement("div");
    actions.className = "orislop-hidden-card__actions";
    const revealButton = document.createElement("button");
    revealButton.type = "button";
    revealButton.textContent = "Show this video";
    revealButton.addEventListener("click", () => revealElement(element, shield));
    const openButton = document.createElement("button");
    openButton.type = "button";
    openButton.textContent = "Open anyway";
    openButton.addEventListener("click", () => window.open(extracted.url, "_blank", "noopener,noreferrer"));
    actions.append(revealButton, openButton);

    shield.append(top, title, reason, actions);
    element.prepend(shield);
  }

  function markQuestionable(element, extracted, score) {
    element.classList.add("orislop-flagged-outline");
    element.classList.add("orislop-side-callout-host");
    const existing = element.querySelector(":scope > .orislop-callout-card");
    if (existing) {
      existing.remove();
    }

    const callout = document.createElement("section");
    callout.className = "orislop-callout-card";
    callout.setAttribute("role", "status");
    callout.setAttribute("aria-live", "polite");
    callout.setAttribute("aria-atomic", "true");

    const label = document.createElement("strong");
    label.textContent = score.recommendation === "skip"
      ? "Orislop rated this Skip (no automatic action taken)"
      : "Orislop marked this video Questionable";

    const detail = document.createElement("span");
    detail.textContent = `${score.score}/100 - ${score.reasons.slice(0, 2).join(", ")}`;

    const dismissButton = document.createElement("button");
    dismissButton.type = "button";
    dismissButton.textContent = "Dismiss for now";
    dismissButton.addEventListener("click", () => {
      if (isCurrentVideoCandidate(element, extracted)) {
        skipController?.cancel({
          videoId: extracted.videoId,
          suppress: true,
          reason: "user_dismissed"
        });
      }
      clearOrislopCallout(element);
      element.setAttribute(PROCESSED_ATTR, "revealed");
    });

    callout.append(label, detail, dismissButton);
    element.prepend(callout);
  }

  function clearOrislopCallout(element) {
    element.classList.remove("orislop-flagged-outline");
    element.classList.remove("orislop-side-callout-host");
    const existing = element.querySelector(":scope > .orislop-callout-card");
    if (existing) {
      existing.remove();
    }
  }

  function revealElement(element, shield) {
    shield.remove();
    restoreElementChildren(element);
    element.setAttribute(PROCESSED_ATTR, "revealed");
  }

  function restoreHiddenCards() {
    for (const shield of document.querySelectorAll(".orislop-hidden-card")) {
      const element = shield.parentElement;
      if (!(element instanceof HTMLElement)) {
        continue;
      }
      shield.remove();
      restoreElementChildren(element);
      element.removeAttribute(PROCESSED_ATTR);
      element.removeAttribute(SIGNATURE_ATTR);
    }
  }

  function rememberChildDisplay(child) {
    if (!child.hasAttribute(CHILD_DISPLAY_ATTR)) {
      child.setAttribute(CHILD_DISPLAY_ATTR, child.style.display || "");
    }
  }

  function restoreElementChildren(element) {
    for (const child of Array.from(element.children)) {
      if (!(child instanceof HTMLElement)) {
        continue;
      }
      if (child.classList.contains("orislop-hidden-card") || child.classList.contains("orislop-hidden-comment")) {
        continue;
      }
      child.style.display = child.getAttribute(CHILD_DISPLAY_ATTR) || "";
      child.removeAttribute(CHILD_DISPLAY_ATTR);
    }
  }

  function rememberPreSkip(extracted, score) {
    if (!settingsCache.autoSkip || score?.recommendation !== "skip" || !extracted.videoId) {
      return;
    }

    preSkipScores.set(extracted.videoId, {
      ...score,
      phase: "pre_skip",
      preSkippedAt: Date.now()
    });

    if (preSkipScores.size > LOOKAHEAD_LIMIT * 2) {
      const oldestKey = preSkipScores.keys().next().value;
      preSkipScores.delete(oldestKey);
    }
  }

  function getCurrentPreSkipScore(element, extracted) {
    if (!settingsCache.autoSkip || !isCurrentVideoCandidate(element, extracted) || !extracted.videoId) {
      return null;
    }

    return preSkipScores.get(extracted.videoId) || null;
  }

  function isActiveShortsScrollerCandidate(_element, extracted) {
    return window.location.pathname.startsWith("/shorts/")
      && extracted.videoId
      && !isCurrentVideoCandidate(_element, extracted);
  }

  function isCurrentVideoCandidate(element, extracted) {
    if (!extracted.videoId) {
      return false;
    }

    const current = parseYouTubeUrl(window.location.href);
    if (current.videoId && current.videoId === extracted.videoId) {
      return true;
    }

    return element.matches("ytd-shorts, ytd-watch-metadata")
      && (window.location.pathname.startsWith("/shorts/") || window.location.pathname === "/watch");
  }

  async function attemptAutoSkip(extracted, score) {
    if (!skipController) {
      return;
    }

    const decision = skipController.start({
      recommendation: score.recommendation,
      autoSkip: settingsCache.autoSkip,
      videoId: extracted.videoId,
      attempt: ({ attemptIndex }) => attemptNavigationStep(attemptIndex)
    });
    if (!decision.allowed) {
      showAutoSkipGuard(extracted, score, decision.reason);
      return;
    }

    skippedThisSession += 1;
    showCurrentSkipShield(extracted, score, {
      statusMessage: `Moving to the next video. Safety stop: ${skippedThisSession}/${MAX_CONSECUTIVE_AUTOSKIPS} consecutive skips.`
    });
    showAutoSkipToast(extracted, score, `Auto-skip started for a Skip-rated video: ${extracted.title || "YouTube video"}.`);
    await saveSkippedRecord(extracted, score, currentVideoKind() === "short" ? "auto_skipped_short" : "auto_skipped_watch");
  }

  function attemptNavigationStep(attemptIndex) {
    return currentVideoKind() === "short"
      ? tryNextShortNavigation(attemptIndex)
      : tryNextWatchNavigation(attemptIndex);
  }

  function tryNextShortNavigation(attemptIndex) {
    if (attemptIndex === 0) {
      return clickFirst([
        "#navigation-button-down button",
        "button[aria-label='Next video']",
        "button[aria-label='Next Short']",
        "button[aria-label='Next']",
        "ytd-button-renderer[aria-label='Next video'] button"
      ]);
    }
    if (attemptIndex === 1) {
      dispatchNavigationKey("ArrowDown", 40);
      return false;
    }
    if (attemptIndex === 2) {
      dispatchNavigationKey("PageDown", 34);
      return false;
    }
    dispatchWheelNavigation();
    return false;
  }

  function tryNextWatchNavigation(attemptIndex) {
    if (attemptIndex === 0) {
      return clickFirst([
        ".ytp-next-button",
        "a.ytp-next-button",
        "button.ytp-next-button",
        "a[aria-label='Next']",
        "button[aria-label='Next']",
        "a[href*='watch?v='][aria-label*='Next']"
      ]);
    }
    if (attemptIndex === 1) {
      dispatchNavigationKey("N", 78, true);
    }
    return false;
  }

  function dispatchNavigationKey(key, keyCode, shiftKey = false) {
    const eventOptions = {
      key,
      code: key === "ArrowDown" ? "ArrowDown" : key === "PageDown" ? "PageDown" : "KeyN",
      keyCode,
      which: keyCode,
      cancelable: true,
      bubbles: true,
      shiftKey
    };
    const active = document.activeElement;
    const isEditing = active instanceof HTMLInputElement
      || active instanceof HTMLTextAreaElement
      || active?.isContentEditable;
    const target = isEditing ? document.body : active || document.body;
    target?.dispatchEvent(new KeyboardEvent("keydown", eventOptions));
    target?.dispatchEvent(new KeyboardEvent("keyup", eventOptions));
  }

  function dispatchWheelNavigation() {
    const event = new WheelEvent("wheel", {
      bubbles: true,
      cancelable: true,
      deltaY: Math.max(window.innerHeight, 900),
      deltaMode: 0
    });
    (document.activeElement || document.documentElement).dispatchEvent(event);
  }

  function clickFirst(selectors) {
    for (const selector of selectors) {
      const target = document.querySelector(selector);
      if (target instanceof HTMLElement && !target.hasAttribute("disabled") && isProbablyVisible(target)) {
        target.click();
        return true;
      }
    }
    return false;
  }

  function showAutoSkipToast(extracted, score, overrideMessage) {
    let toast = document.getElementById(TOAST_ID);
    if (!toast) {
      toast = document.createElement("aside");
      toast.id = TOAST_ID;
      toast.className = "orislop-autoskip-toast";
      toast.setAttribute("role", "status");
      toast.setAttribute("aria-live", "polite");
      toast.setAttribute("aria-atomic", "true");
      document.documentElement.append(toast);
    }

    toast.textContent = overrideMessage
      || `Orislop auto-skipped: ${extracted.title || "YouTube video"} (${score.score}/100)`;
    window.clearTimeout(showAutoSkipToast.timeoutId);
    showAutoSkipToast.timeoutId = window.setTimeout(() => {
      toast?.remove();
    }, 4200);
  }

  function showCurrentSkipShield(extracted, score, { statusMessage = "Orislop is moving to the next video.", allowResume = false } = {}) {
    let shield = document.getElementById(CURRENT_SKIP_SHIELD_ID);
    if (!shield) {
      focusBeforeSkipShield = document.activeElement instanceof HTMLElement ? document.activeElement : null;
      shield = document.createElement("aside");
      shield.id = CURRENT_SKIP_SHIELD_ID;
      shield.className = "orislop-current-skip-shield";
      shield.setAttribute("role", "alertdialog");
      shield.setAttribute("aria-modal", "true");
      shield.setAttribute("aria-live", "assertive");
      shield.setAttribute("aria-atomic", "true");
      shield.setAttribute("aria-labelledby", "orislop-skip-shield-title");
      shield.setAttribute("aria-describedby", "orislop-skip-shield-detail orislop-skip-shield-status");
      document.documentElement.append(shield);
    }

    shield.dataset.videoId = extracted.videoId || "";
    shield.innerHTML = "";
    const badge = document.createElement("span");
    badge.className = "orislop-current-skip-shield__badge";
    badge.textContent = score.reasons.includes("YouTube AI/synthetic disclosure")
      ? "AI disclosure detected"
      : "Skip-rated video";

    const title = document.createElement("strong");
    title.id = "orislop-skip-shield-title";
    title.textContent = extracted.title || "YouTube video";

    const detail = document.createElement("p");
    detail.id = "orislop-skip-shield-detail";
    detail.textContent = `${score.score}/100 - ${score.reasons.slice(0, 2).join(", ")}`;

    const status = document.createElement("small");
    status.id = "orislop-skip-shield-status";
    status.textContent = statusMessage;

    const watchAnyway = document.createElement("button");
    watchAnyway.type = "button";
    watchAnyway.textContent = "Watch anyway";
    const watchAnywayAction = (message = "Watch anyway selected. Orislop will not skip this video again this session.") => {
      skipController?.cancel({
        videoId: extracted.videoId,
        suppress: true,
        reason: "watch_anyway"
      });
      preSkipScores.delete(extracted.videoId);
      removeCurrentSkipShield();
      showAutoSkipToast(extracted, score, message);
    };
    shield._orislopWatchAnyway = watchAnywayAction;
    watchAnyway.addEventListener("click", () => watchAnywayAction());

    shield.append(badge, title, detail, status, watchAnyway);
    if (allowResume) {
      const resume = document.createElement("button");
      resume.type = "button";
      resume.textContent = "Resume auto-skip";
      resume.addEventListener("click", () => {
        skipController?.resume();
        removeCurrentSkipShield({ restoreFocus: false });
        void attemptAutoSkip(extracted, score);
      });
      shield.append(resume);
    }
    window.requestAnimationFrame(() => watchAnyway.focus({ preventScroll: true }));
  }

  function showAutoSkipGuard(extracted, score, reason) {
    if (!["max_consecutive", "revisit", "suppressed"].includes(reason)) {
      return;
    }
    const statusMessage = reason === "max_consecutive"
      ? `Safety pause: Orislop stopped after ${MAX_CONSECUTIVE_AUTOSKIPS} consecutive auto-skips. Choose Resume auto-skip to continue.`
      : reason === "revisit"
        ? "Revisit protected: you returned to a previously skipped video, so Orislop will not move you away again this session."
        : "This video is protected for the rest of this session because you chose to keep watching it.";
    showCurrentSkipShield(extracted, score, {
      statusMessage,
      allowResume: reason === "max_consecutive"
    });
    showAutoSkipToast(extracted, score, statusMessage);
  }

  function handleSkipControllerState(event) {
    if (event.type !== "navigation_stopped") {
      return;
    }
    if (event.reason === "navigation_started") {
      updateCurrentSkipShield("A next-video control was activated. Waiting for YouTube to finish navigation.");
      return;
    }
    if (event.reason === "navigation_failed") {
      updateCurrentSkipShield("YouTube did not expose a working next-video control. No more navigation attempts will run for this video.");
      return;
    }
    if (event.reason === "video_changed") {
      removeCurrentSkipShield();
    }
  }

  function updateCurrentSkipShield(message) {
    const shield = document.getElementById(CURRENT_SKIP_SHIELD_ID);
    if (!shield) {
      return;
    }
    const status = shield.querySelector("small");
    if (status) {
      status.textContent = message;
    }
  }

  function removeCurrentSkipShield({ restoreFocus = true } = {}) {
    const shield = document.getElementById(CURRENT_SKIP_SHIELD_ID);
    if (!shield) {
      return;
    }
    shield._orislopWatchAnyway = null;
    shield.remove();
    if (restoreFocus && focusBeforeSkipShield?.isConnected) {
      focusBeforeSkipShield.focus({ preventScroll: true });
    }
    focusBeforeSkipShield = null;
  }

  function currentVideoKind() {
    return window.location.pathname.startsWith("/shorts/") ? "short" : "watch";
  }

  async function saveFlaggedRecord(extracted, score) {
    const record = {
      id: `${extracted.videoId || extracted.url}:${score.recommendation}`,
      videoId: extracted.videoId,
      url: extracted.url,
      title: extracted.title || "YouTube video",
      recommendation: score.recommendation,
      score: score.score,
      reasons: score.reasons,
      createdAt: new Date().toISOString()
    };

    if (!historyWriter) {
      return;
    }
    await historyWriter.append(
      FLAGGED_KEY,
      record,
      (item) => `${item.videoId || item.url}:${item.recommendation}`
    );
  }

  async function readFlaggedLog() {
    return readList(FLAGGED_KEY);
  }

  async function saveSkippedRecord(extracted, score, mode) {
    const record = {
      id: `${extracted.videoId || extracted.url}:${mode}`,
      videoId: extracted.videoId,
      url: extracted.url,
      title: extracted.title || "YouTube video",
      mode,
      score: score.score,
      reasons: score.reasons,
      createdAt: new Date().toISOString()
    };

    if (!historyWriter) {
      return;
    }
    await historyWriter.append(
      SKIPPED_KEY,
      record,
      (item) => `${item.videoId || item.url}:${item.mode}`
    );
  }

  function dedupeFlaggedRecords(records) {
    return dedupeRecords(records, (record) => `${record.videoId || record.url}:${record.recommendation}`);
  }

  async function readList(key) {
    try {
      const result = await chrome.storage.local.get(key);
      return Array.isArray(result[key]) ? result[key] : [];
    } catch {
      return [];
    }
  }

  async function loadSettings() {
    try {
      const result = await chrome.storage.local.get(SETTINGS_KEY);
      return normalizeSettings(result[SETTINGS_KEY]);
    } catch {
      return { ...DEFAULT_SETTINGS };
    }
  }

  function normalizeSettings(value) {
    if (!value || typeof value !== "object") {
      return { ...DEFAULT_SETTINGS };
    }
    return {
      autoSkip: typeof value.autoSkip === "boolean" ? value.autoSkip : DEFAULT_SETTINGS.autoSkip,
      hideFeedCards: typeof value.hideFeedCards === "boolean" ? value.hideFeedCards : DEFAULT_SETTINGS.hideFeedCards,
      hideBotComments: typeof value.hideBotComments === "boolean" ? value.hideBotComments : DEFAULT_SETTINGS.hideBotComments,
      advancedDetection: typeof value.advancedDetection === "boolean" ? value.advancedDetection : DEFAULT_SETTINGS.advancedDetection
    };
  }

  function dedupeRecords(records, keyFor) {
    const seen = new Set();
    const deduped = [];
    for (const record of records) {
      const key = keyFor(record);
      if (seen.has(key)) {
        continue;
      }
      seen.add(key);
      deduped.push(record);
    }
    return deduped;
  }

  function scoreStaticSlop(input) {
    const parsed = parseYouTubeUrl(input.url);
    if (!parsed.videoId) {
      return {
        score: 0,
        recommendation: "watch",
        reasons: ["Enter a valid YouTube URL to score this item"],
        signalBreakdown: [],
        confidence: "low",
        videoId: null,
        videoKind: "unknown",
        baseScore: 0,
        stackedSignalBoost: 0,
        strictnessMultiplier: 1,
        thresholds: THRESHOLDS
      };
    }

    const text = normalize([
      input.title,
      input.description,
      parsed.videoKind === "short" ? "youtube shorts" : ""
    ].filter(Boolean).join(" "));
    const reasons = [];
    const signalBreakdown = [];
    let rawScore = 0;

    for (const rule of RULES) {
      if (rule.test(text, input)) {
        rawScore += rule.weight;
        reasons.push(rule.label);
        signalBreakdown.push({
          label: rule.label,
          points: rule.weight
        });
      }
    }

    const boostableSignalCount = reasons.filter((reason) => ![
      "Shorts format signal",
      "Satisfying/ASMR filler context"
    ].includes(reason)).length;
    const stackedSignalBoost = Math.max(0, boostableSignalCount - 2) * 4;
    const hasAiDisclosure = reasons.includes("YouTube AI/synthetic disclosure");
    const score = hasAiDisclosure ? 100 : clampScore(rawScore + stackedSignalBoost);
    const recommendation = hasAiDisclosure || score >= THRESHOLDS.skip ? "skip" : score >= THRESHOLDS.questionable ? "questionable" : "watch";
    const confidence = reasons.length >= 4 ? "high" : reasons.length >= 2 ? "medium" : "low";

    const heuristicResult = {
      score,
      recommendation,
      reasons: reasons.length > 0 ? reasons : ["No strong static slop signals found"],
      signalBreakdown,
      confidence,
      videoId: parsed.videoId,
      videoKind: parsed.videoKind,
      baseScore: rawScore,
      stackedSignalBoost,
      strictnessMultiplier: 1,
      thresholds: THRESHOLDS
    };
    return combineScore(input, heuristicResult);
  }

  function combineScore(input, heuristic) {
    const ai = runAiClassifier({
      title: input.title,
      description: input.description,
      channelName: input.channelName,
      durationSeconds: input.durationSeconds,
      isShort: heuristic.videoKind === "short"
    });
    const transcriptScore = null;
    const channelRisk = scoreChannelRisk(input.channelName || "");
    const hardAiDisclosure = heuristic.reasons.includes("YouTube AI/synthetic disclosure");
    const aiSourceScore = ai.available ? ai.score : heuristic.score;
    const finalScore = hardAiDisclosure ? 100 : clampScore(
      heuristic.score * 0.35
      + aiSourceScore * 0.45
      + (transcriptScore ?? heuristic.score) * 0.15
      + channelRisk * 0.05
    );
    const recommendation = finalScore >= THRESHOLDS.skip ? "skip" : finalScore >= THRESHOLDS.questionable ? "questionable" : "watch";
    const reasons = [
      ...heuristic.reasons.filter((reason) => reason !== "No strong static slop signals found").slice(0, 3),
      ...(ai.available ? [`AI classifier: ${ai.predictedLabel} (${ai.score}/100)`] : []),
      ...ai.topFeatures.slice(0, 2).map((feature) => `AI feature: ${feature.term} ${feature.contribution >= 0 ? "+" : ""}${feature.contribution}`)
    ];
    return {
      ...heuristic,
      score: finalScore,
      recommendation,
      reasons: reasons.length > 0 ? reasons : ["No strong combined slop signals found"],
      confidence: confidenceForCombined(heuristic, ai, finalScore),
      aiClassifierUsed: ai.available,
      spatiotemporalUsed: false,
      sourceScores: {
        heuristic: heuristic.score,
        aiClassifier: ai.available ? ai.score : null,
        transcript: transcriptScore,
        channelRisk,
        spatiotemporal: null
      },
      aiClassifier: ai,
      fallbackReasons: [
        ...(!ai.available ? [ai.reason] : []),
        "Spatiotemporal detector was not run in the browser extension path."
      ]
    };
  }

  function runAiClassifier(input) {
    if (!AI_MODEL_AVAILABLE) {
      return {
        available: false,
        modelId: AI_MODEL_ID,
        slopProbability: 0,
        score: 0,
        predictedLabel: "unavailable",
        confidence: "low",
        topFeatures: [],
        reason: "The generated local AI model was not loaded."
      };
    }
    const terms = extractAiTerms(input);
    const counts = new Map();
    for (const term of terms) {
      if (AI_FEATURE_MAP.has(term)) {
        counts.set(term, (counts.get(term) || 0) + 1);
      }
    }
    if (counts.size === 0) {
      const probability = sigmoid(AI_MODEL_INTERCEPT);
      return {
        available: true,
        modelId: AI_MODEL_ID,
        slopProbability: probability,
        score: Math.round(probability * 100),
        predictedLabel: "not_slop",
        confidence: "low",
        topFeatures: []
      };
    }
    const total = Array.from(counts.values()).reduce((sum, value) => sum + value, 0);
    const weighted = [];
    for (const [term, count] of counts) {
      const feature = AI_FEATURE_MAP.get(term);
      weighted.push([term, (count / total) * feature.idf, feature.weight]);
    }
    const norm = Math.sqrt(weighted.reduce((sum, [, value]) => sum + value * value, 0)) || 1;
    const contributions = weighted
      .map(([term, value, weight]) => ({ term, contribution: (value * weight) / norm }));
    const topFeatures = contributions
      .map((feature) => ({ term: feature.term, contribution: Number(feature.contribution.toFixed(3)) }))
      .sort((left, right) => Math.abs(right.contribution) - Math.abs(left.contribution))
      .slice(0, 5);
    const linear = AI_MODEL_INTERCEPT + contributions.reduce((sum, feature) => sum + feature.contribution, 0);
    const probability = sigmoid(linear);
    return {
      available: true,
      modelId: AI_MODEL_ID,
      slopProbability: probability,
      score: Math.round(probability * 100),
      predictedLabel: predictAiLabel(input, topFeatures, probability),
      confidence: Math.abs(probability - AI_MODEL_THRESHOLD) > 0.22 ? "medium" : "low",
      topFeatures
    };
  }

  function extractAiTerms(input) {
    const text = [
      input.title,
      input.description,
      input.channelName,
      ...(input.matchedSignals || [])
    ].filter(Boolean).join(" ");
    const tokens = (text.toLowerCase().match(/[a-z0-9][a-z0-9_'-]*/g) || [])
      .filter((token) => token.length > 1 && !AI_STOP_WORDS.has(token));
    const terms = [...tokens, ...tokens.slice(0, -1).map((token, index) => `${token}_${tokens[index + 1]}`)];
    terms.push(input.isShort ? "__short__" : "__watch__");
    if (input.durationSeconds >= 1800) {
      terms.push("__duration_long__");
    } else if (input.durationSeconds > 0 && input.durationSeconds <= 75) {
      terms.push("__duration_short__");
    } else if (input.durationSeconds > 0) {
      terms.push("__duration_medium__");
    }
    return terms;
  }

  function predictAiLabel(input, topFeatures, probability) {
    const text = [input.title, input.description, input.channelName, ...topFeatures.map((feature) => feature.term)].join(" ").toLowerCase();
    if (probability < AI_MODEL_THRESHOLD) {
      return /\b(science|explains|tutorial|history|math|educational)\b/.test(text) ? "normal_educational" : "not_slop";
    }
    if (/\b(reddit|aita|story|minecraft|parkour|tts)\b/.test(text)) return "reddit_story";
    if (/\b(ai|voice|synthetic|deepfake|generated)\b/.test(text)) return "ai_voice";
    if (/\b(guaranteed|banks|doctors|cure|miracle|secret|trick)\b/.test(text)) return "scam_bait";
    if (/\b(repost|compilation|clips|source|unknown|credit|no_commentary)\b/.test(text)) return "repost_compilation";
    if (/\b(brainrot|subway|surfers|split|screen|viral|ranking)\b/.test(text)) return "brainrot_format";
    return "slop";
  }

  function scoreTranscript(text) {
    const normalized = normalize(text || "");
    if (normalized.length < 24) return null;
    let score = 0;
    if (/\b(ai voice|text to speech|tts|robot voice|synthetic voice)\b/.test(normalized)) score += 35;
    if (/\b(reddit|aita|storytime|askreddit)\b/.test(normalized)) score += 22;
    if (/\b(guaranteed|miracle|doctors hate|banks hate|secret trick|make money fast)\b/.test(normalized)) score += 34;
    return clampScore(score);
  }

  function scoreChannelRisk(channelName) {
    const text = normalize(channelName || "");
    let score = 0;
    if (/\b(bot|repost|vault|clips|compilation|viral loop|story bot|shortcut|secret)\b/.test(text)) score += 45;
    if (/\b(lab|class|tutor|science|history|repair|kitchen|studio|notes)\b/.test(text)) score -= 24;
    return clampScore(score);
  }

  function confidenceForCombined(heuristic, ai, finalScore) {
    if (heuristic.score >= 60 && ai.score >= 60 && finalScore >= 60) return "high";
    if (heuristic.score < 30 && ai.score < 30 && finalScore < 30) return "high";
    return ai.confidence === "low" ? heuristic.confidence : "medium";
  }

  function parseYouTubeUrl(input) {
    const trimmed = String(input || "").trim();
    if (!trimmed) {
      return emptyParsedResult(input);
    }

    try {
      const url = new URL(trimmed.startsWith("http") ? trimmed : `https://${trimmed}`);
      const host = url.hostname.toLowerCase();
      const isYouTubeUrl = ["youtube.com", "www.youtube.com", "m.youtube.com", "youtu.be"].includes(host);
      if (!isYouTubeUrl) {
        return emptyParsedResult(input);
      }

      const pathParts = url.pathname.split("/").filter(Boolean);
      const shortsId = pathParts[0] === "shorts" && pathParts[1] ? decodeURIComponent(pathParts[1]) : null;
      const watchId = url.pathname === "/watch" ? url.searchParams.get("v") : null;
      const shortLinkId = host === "youtu.be" && pathParts[0] ? decodeURIComponent(pathParts[0]) : null;
      const videoId = sanitizeVideoId(shortsId || watchId || shortLinkId);
      const videoKind = shortsId ? "short" : videoId ? "watch" : "unknown";

      return {
        isYouTubeUrl: true,
        videoId,
        videoKind,
        normalizedUrl: videoId
          ? videoKind === "short"
            ? `https://www.youtube.com/shorts/${encodeURIComponent(videoId)}`
            : `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`
          : null
      };
    } catch {
      return emptyParsedResult(input);
    }
  }

  function sanitizeVideoId(value) {
    if (!value) {
      return null;
    }
    const clean = value.trim();
    return /^[a-zA-Z0-9_-]{3,128}$/.test(clean) ? clean : null;
  }

  function emptyParsedResult() {
    return {
      isYouTubeUrl: false,
      videoId: null,
      videoKind: "unknown",
      normalizedUrl: null
    };
  }

  function includesAny(text, phrases) {
    return phrases.some((phrase) => text.includes(phrase));
  }

  function hasPlatformAiDisclosure(text) {
    return includesAny(normalize(text), PLATFORM_AI_DISCLOSURES);
  }

  function isRedditTtsBackgroundFormat(text) {
    const hasStorySource = /\b(reddit|askreddit|aita|storytime|story|stories|thread)\b/.test(text);
    const hasBackgroundVideo = /\b(minecraft|parkour|subway surfers|mobile game|gameplay|satisfying background|silent minecraft parkour)\b/.test(text);
    const hasSyntheticNarration = /\b(text to speech|tts|ai voice|robot voice|voiceover)\b/.test(text);
    return hasStorySource && (hasBackgroundVideo || hasSyntheticNarration);
  }

  function isAiNarration(text) {
    return /\b(ai voice|ai voiceover|ai voice over|text to speech|tts|robot voice|synthetic voice|voice clone)\b/.test(text);
  }

  function hasStackedSlopFormat(text) {
    const hasStory = /\b(reddit|askreddit|aita|story|stories|thread)\b/.test(text);
    const hasBackground = /\b(minecraft|parkour|subway surfers|mobile game|gameplay)\b/.test(text);
    const hasSyntheticNarration = /\b(text to speech|tts|ai voice|robot voice|voiceover|narration)\b/.test(text);
    const hasLowOriginalitySource = /\b(viral clips|clips compilation|family guy clips|repost|reuploaded|re-upload|source unknown|credit unknown|not mine|no commentary|green screen|greenscreen)\b/.test(text);
    return [hasStory, hasBackground, hasSyntheticNarration, hasLowOriginalitySource].filter(Boolean).length >= 2;
  }

  function isLongLowOriginalityCompilation(text) {
    const hasLongDuration = /\b([1-9]|1[0-2])\s*(hour|hours|hr|hrs)\b/.test(text);
    const hasLowOriginalityTopic = /\b(reddit|stories|story|minecraft|parkour|subway surfers|viral clips|clips compilation|source unknown|credit unknown|not mine|repost|reupload|text to speech|tts|ai voice|robot voice)\b/.test(text)
      || (/\b(compilation|clips)\b/.test(text) && /\b(no commentary|source unknown|credit unknown|viral|ai voice|tts|repost|reupload)\b/.test(text));
    return hasLongDuration && hasLowOriginalityTopic;
  }

  function isSensoryFiller(text) {
    return includesAny(text, SENSORY_FILLER) && !isSongOrLyricsContext(text);
  }

  function isRankedSensoryList(text) {
    return isSensoryFiller(text)
      && /\b(ranking|ranked|top\s*\d+|most satisfying|best satisfying|satisfying compilation|asmr compilation)\b/.test(text);
  }

  function hasAiSignal(text) {
    if (includesAny(text, PLATFORM_AI_DISCLOSURES)) {
      return true;
    }
    if (includesAny(text, AI_TERMS.filter((term) => term !== "ai"))) {
      return true;
    }
    return /\bai\b/.test(text)
      && /\b(voice|generated|synthetic|deepfake|clone|cover|song|music|video|image|art|made|created|altered)\b/.test(text);
  }

  function emojiCount(text) {
    return Array.from(text).filter((char) => /\p{Extended_Pictographic}/u.test(char)).length;
  }

  function allCapsWordCount(text) {
    return text.split(/\s+/).filter((word) => /^[A-Z]{4,}$/.test(word)).length;
  }

  function hasRepetition(text) {
    const words = text.match(/[a-z0-9']+/gi)?.map((word) => word.toLowerCase()) || [];
    if (words.length < 10) {
      return false;
    }

    const uniqueRatio = new Set(words).size / words.length;
    const counts = new Map();
    for (let index = 0; index < words.length - 1; index += 1) {
      const key = `${words[index]} ${words[index + 1]}`;
      counts.set(key, (counts.get(key) || 0) + 1);
    }

    return uniqueRatio < 0.45 || Array.from(counts.values()).some((count) => count >= 3);
  }

  function isSongOrLyricsContext(text) {
    return /\b(song|songs|lyrics|chorus|verse|hook|music|track|cover|remix|karaoke|performance|practice)\b/.test(text);
  }

  function isLowInformationTitle(title) {
    const trimmed = title.trim();
    if (!trimmed) {
      return false;
    }

    const tokens = trimmed.split(/\s+/).filter(Boolean);
    const hashtagTokens = tokens.filter((token) => /^#[a-zA-Z0-9_-]+$/.test(token));
    return trimmed.length < 12
      || (tokens.length >= 2 && hashtagTokens.length === tokens.length)
      || (tokens.length >= 4 && hashtagTokens.length / tokens.length >= 0.75);
  }

  function isProbablyVisible(element) {
    const rect = element.getBoundingClientRect();
    return rect.width > 40
      && rect.height > 30
      && rect.bottom >= -300
      && rect.top <= window.innerHeight + 900;
  }

  function normalize(value) {
    return String(value || "").toLowerCase().replace(/\s+/g, " ").trim();
  }

  function normalizeWhitespace(value) {
    return String(value || "").replace(/\s+/g, " ").trim();
  }

  function sigmoid(value) {
    if (value >= 0) {
      const z = Math.exp(-value);
      return 1 / (1 + z);
    }
    const z = Math.exp(value);
    return z / (1 + z);
  }

  function clampScore(value) {
    return Math.max(0, Math.min(100, Math.round(value)));
  }
})();
